---
- name: Install vim and create info.txt
  hosts: all
  become: yes
  tasks:
    - name: Ensure vim is installed
      yum:
        name: vim
        state: present

    - name: Ensure /opt/devops directory exists
      file:
        path: /opt/devops
        state: directory

    - name: Create info.txt with custom content
      copy:
        content: "Hello from Ansible!\n"
        dest: /opt/devops/info.txt

